apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: revworkforce
data:
  SPRING_PROFILES_ACTIVE: prod
  CONFIG_SERVER_URL: http://config-server:8888
  EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  MYSQL_URL: jdbc:mysql://mysql:3306/
