server.port=8888
spring.application.name=config-server

# Use GitHub for configuration
spring.cloud.config.server.git.uri=https://github.com/RevWorkForceTeam/RevWorkForce-Config.git
spring.cloud.config.server.git.clone-on-start=true